services: docker
git:
  depth: false
install: make docker-login build-docker
stages:
- name: publish-docker
jobs:
  include:
  - stage: publish
    name: Publish docker image
    script:
    - make docker-login publish-docker
env:
  global:
  - secure: WZPCFAfyErmb0VQcrDHYAb9joMsDkVcZHbAqypkOs+Nnj0QAdxU1n2hnJmDDpuraHis2UjLBKLTznNGqhPcDSxm5CmuTZog94juEbfARp4kXPX2o7XbAtYOnBJz21NiEmsrOsDgd4PBkaX84luZ2OSzzG9keOWhJ4IEni+LEPnNraa1wTtemLu8p+zNsiD8cr03nmroQcfqznZDmO77Y7LuCTPxYc3ubvBgoeKWJOuXqSMsL8v7hKd1w5837TL4d/0xn8z34TgnhSZ16cvE3IqOLZ8NVFew/pI+UlYM3rQ9rRzV1djeynaA+uBXf5JOZ9NHk2uJVYx2YqbRBCkyfUWCXfN+sx++lqfA5RxQimW3G3bgC7KkzQrAk5rX2BsNGnBFh4HltX2h8OMTC0VZEqGOczl0J05knFu0EvPtpJSvuofAD0WvwZg0+s8BWmTqupr1diT2Q7Qb3cn8V/UFs3jNRV9rt99DkJcH1BlIs22kZqxTC5WqQkKcSy9S3CWSBmulKdZoydM1l88/kBQ3Z7YM0WgTISzbRypvtTCA6j5oSs0xITSzfPFdcfKl79FMgm76tqU1F766Ud5XRO9yfmB/kTHj0UrQjK2TZOI8ugZf8g9OmtPelJKfLI1HpaQDcoego2f+NTAaQieQmAuSC/+Y/JN+wftO9hmcEQrUlnH4=
  - secure: H6Qooy9DzSwrHLERjA9gP0fC8jEhDwsMWRa8C1OzOJf1PPe9ryaRdz/rbIHRzA/Vr+sUFxc7nWjEfFjDu+Vu6vKLFtLR0Teza81TYHECmqBRMw8zCjBdn7ES1milz8FlTPvys7WlhfK/F2OV/HAiUNvmleQcnOHvfRc0PLpoItV9YIn5mttSxiVt6OE5CT48n8WcGO0LhOC7uvDQUtbtcsE7n1nDu3LWxf0NzjylmYjcidgx9n0OWZyQdji7YyTkIIzdUuGuyR0wQnbYwMMBxP5MQ4smWpX0tkD6x47BH7T5YOtLMCHN0m1NlP6altn9FgTEku6afToK3NRUkA2ATFRaUOhIOf7m0PTFvSIlPL2u5cjT77VyE4ZR32W/t9cfE1SVcazrQWp+egKvgwrBTpRQ60lqoIz+xdwiyZDQ6xXefRstqvLm6P4eYCIlGMeBMC5TtYx9arQ9ogWe1/NFgE6gl8msAvC7Wf1bR2FtdlfNjHrEqRfvyFrbzj7XeogMa0ppcePHSm/sUQDNLpBFOenHbTKZWZNM5dBU7rgubf/ITB+GS7EfcOiaqr/bfN61pnUSrjw4SBvE9msSNp0o5QlHa8IW5So/UFCgu/v8aslLkVIz9RVQz9m+g3n40IyFeH8uC1d+tAFNEgtKREgPGYbgygVSHj+JUU3k344OW/E=
